export const chats = [
    {
      id: 1,
      name: 'Sarah Chen',
      avatar: 'SC',
      lastMessage: 'Hey! About tomorrow\'s class schedule...',
      timestamp: '14:30',
      unread: true,
      unreadCount: 2,
    },
    {
      id: 2,
      name: 'Mike Johnson',
      avatar: 'MJ',
      lastMessage: 'Want to grab coffee this weekend?',
      timestamp: 'Yesterday',
      unread: false,
    },
    {
      id: 3,
      name: 'Emma Wilson',
      avatar: 'EW',
      lastMessage: 'Thanks for your help with the assignment!',
      timestamp: 'Monday',
      unread: false,
    },
    {
      id: 4,
      name: 'David Kim',
      avatar: 'DK',
      lastMessage: 'When is our next group discussion?',
      timestamp: 'Last week',
      unread: true,
      unreadCount: 1,
    },
    {
      id: 5,
      name: 'Lisa Park',
      avatar: 'LP',
      lastMessage: 'The study materials are ready to share.',
      timestamp: '2 hours ago',
      unread: false,
    },
    {
      id: 6,
      name: 'Alex Thompson',
      avatar: 'AT',
      lastMessage: 'Great job on the presentation!',
      timestamp: '3 hours ago',
      unread: true,
      unreadCount: 3,
    },
    {
      id: 7,
      name: 'Rachel Green',
      avatar: 'RG',
      lastMessage: 'Can you send me the notes from today?',
      timestamp: '5 hours ago',
      unread: false,
    },
    {
      id: 8,
      name: 'Tom Anderson',
      avatar: 'TA',
      lastMessage: 'Let\'s meet at the library tomorrow.',
      timestamp: '1 day ago',
      unread: false,
    },
  ];