  // Mock data for different post types
  // 用当前时间为基准，依次减去对应小时/天数，生成ISO字符串
  const now = new Date();
  function hoursAgo(h: number) {
    const d = new Date(now.getTime() - h * 60 * 60 * 1000);
    return d.toISOString();
  }
  function daysAgo(dn: number) {
    const d = new Date(now.getTime() - dn * 24 * 60 * 60 * 1000);
    return d.toISOString();
  }
  export const allPosts = [
    {
      id: 1,
      type: 'share',
      author: 'Sarah Chen',
      authorId: 'sarah-chen',
      avatar: 'SC',
      timestamp: hoursAgo(2),
      scope: 'campus',
      title: 'Amazing study spot found!',
      content: 'Just discovered this quiet corner in the library with perfect lighting. Great for late-night study sessions! 📚✨',
      image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&h=300&fit=crop',
      likes: 24,
      comments: 8,
    },
    {
      id: 2,
      type: 'event',
      author: 'Campus Events',
      authorId: 'campus-events',
      avatar: 'CE',
      timestamp: hoursAgo(4),
      scope: 'campus',
      title: 'Spring Festival Meetup',
      content: 'Join us for traditional food, games, and cultural exchange!',
      eventTime: 'Feb 15, 7:00 PM',
      location: 'Student Center',
      capacity: '50 spots left',
      likes: 56,
      comments: 12,
    },
    {
      id: 3,
      type: 'marketplace',
      author: 'Mike Johnson',
      authorId: 'mike-johnson',
      avatar: 'MJ',
      timestamp: hoursAgo(6),
      scope: 'department',
      title: 'MacBook Pro 2021',
      content: 'Selling my MacBook Pro, excellent condition, comes with original charger.',
      price: '$1,200',
      image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=300&fit=crop',
      likes: 18,
      comments: 5,
    },
    // 新增全香港范围的帖子
    {
      id: 1001,
      type: 'share',
      author: 'HK News',
      authorId: 'hk-news',
      avatar: 'HK',
      timestamp: hoursAgo(1),
      scope: 'hongkong',
      title: 'Hong Kong-wide event: Science Expo',
      content: 'The largest science expo in Hong Kong is coming this weekend! Don’t miss out!',
      image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?w=400&h=300&fit=crop',
      likes: 99,
      comments: 30,
    },
    {
      id: 1002,
      type: 'event',
      author: 'HK Sports',
      authorId: 'hk-sports',
      avatar: 'HS',
      timestamp: daysAgo(1),
      scope: 'hongkong',
      title: 'Hong Kong Marathon',
      content: 'Annual marathon open to all Hong Kong residents.',
      eventTime: 'Aug 1, 7:00 AM',
      location: 'Victoria Park',
      capacity: '10,000 runners',
      likes: 200,
      comments: 80,
    },
    {
      id: 4,
      type: 'share',
      author: 'Emma Wilson',
      authorId: 'emma-wilson',
      avatar: 'EW',
      timestamp: daysAgo(1),
      scope: 'department',
      title: 'Coffee shop recommendation',
      content: 'Found this amazing coffee shop near campus. Their lattes are incredible! ☕',
      image: 'https://images.unsplash.com/photo-1501332306681-4d5b2f0e9515?w=400&h=300&fit=crop',
      likes: 32,
      comments: 15,
    },
    {
      id: 5,
      type: 'event',
      author: 'Tech Club',
      authorId: 'tech-club',
      avatar: 'TC',
      timestamp: daysAgo(2),
      scope: 'department',
      title: 'Hackathon 2024',
      content: '48-hour coding challenge with amazing prizes! All skill levels welcome.',
      eventTime: 'Mar 1-3, 2024',
      location: 'Engineering Building',
      capacity: '100 spots left',
      likes: 89,
      comments: 23,
    },
    // Campus Share posts
    {
      id: 6,
      type: 'share',
      author: 'Alex Thompson',
      authorId: 'alex-thompson',
      avatar: 'AT',
      timestamp: hoursAgo(3),
      scope: 'campus',
      title: 'Best study playlist',
      content: 'Created a perfect playlist for studying. Lo-fi beats really help me focus! 🎵',
      image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop',
      likes: 45,
      comments: 11,
    },
    {
      id: 7,
      type: 'share',
      author: 'Lisa Park',
      authorId: 'lisa-park',
      avatar: 'LP',
      timestamp: hoursAgo(5),
      scope: 'department',
      title: 'Campus photography',
      content: 'Beautiful sunset at the main quad today. Campus looks magical! 📸',
      image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400&h=300&fit=crop',
      likes: 67,
      comments: 9,
    },
    {
      id: 8,
      type: 'share',
      author: 'David Kim',
      authorId: 'david-kim',
      avatar: 'DK',
      timestamp: daysAgo(1),
      scope: 'campus',
      title: 'Study group success',
      content: 'Our study group just aced the midterm! Teamwork makes the dream work! 📚',
      image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop',
      likes: 38,
      comments: 7,
    },
    // Events posts
    {
      id: 9,
      type: 'event',
      author: 'Music Society',
      authorId: 'music-society',
      avatar: 'MS',
      timestamp: daysAgo(1),
      scope: 'campus',
      title: 'Jazz Night Concert',
      content: 'Live jazz performance featuring student musicians. Free admission!',
      eventTime: 'Feb 20, 8:00 PM',
      location: 'Auditorium',
      capacity: '200 spots left',
      likes: 123,
      comments: 28,
    },
    {
      id: 10,
      type: 'event',
      author: 'Sports Club',
      authorId: 'sports-club',
      avatar: 'SC',
      timestamp: daysAgo(2),
      scope: 'department',
      title: 'Basketball Tournament',
      content: 'Inter-department basketball tournament. Sign up your team now!',
      eventTime: 'Feb 25, 2:00 PM',
      location: 'Gymnasium',
      capacity: '16 teams max',
      likes: 95,
      comments: 19,
    },
    {
      id: 11,
      type: 'event',
      author: 'Career Center',
      authorId: 'career-center',
      avatar: 'CC',
      timestamp: daysAgo(3),
      scope: 'campus',
      title: 'Career Fair 2024',
      content: 'Meet top employers and find your dream job. Bring your resume!',
      eventTime: 'Mar 10, 10:00 AM',
      location: 'Convention Hall',
      capacity: '500 spots left',
      likes: 234,
      comments: 45,
    },
    // Marketplace posts
    {
      id: 12,
      type: 'marketplace',
      author: 'Jenny Lee',
      authorId: 'jenny-lee',
      avatar: 'JL',
      timestamp: hoursAgo(4),
      scope: 'department',
      title: 'Textbooks - Math 101',
      content: 'Selling Calculus textbook, barely used, includes solution manual.',
      price: '$45',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
      likes: 12,
      comments: 3,
    },
    {
      id: 13,
      type: 'marketplace',
      author: 'Tom Anderson',
      authorId: 'tom-anderson',
      avatar: 'TA',
      timestamp: hoursAgo(8),
      title: 'Bicycle for sale',
      content: 'Mountain bike in great condition, perfect for campus commuting.',
      price: '$180',
      image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=300&fit=crop',
      likes: 29,
      comments: 6,
    },
    {
      id: 14,
      type: 'marketplace',
      author: 'Rachel Green',
      authorId: 'rachel-green',
      avatar: 'RG',
      timestamp: daysAgo(1),
      title: 'Furniture set',
      content: 'Complete bedroom set: bed, desk, chair, and wardrobe.',
      price: '$350',
      image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop',
      likes: 41,
      comments: 8,
    },
    {
      id: 15,
      type: 'marketplace',
      author: 'Chris Wong',
      authorId: 'chris-wong',
      avatar: 'CW',
      timestamp: daysAgo(2),
      title: 'Gaming console',
      content: 'PS5 with 2 controllers and 5 games. Moving out sale!',
      price: '$400',
      image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&h=300&fit=crop',
      likes: 78,
      comments: 15,
    },
  ];